### ISSUE TITLE
Question about 'process_ava.py'

### ISSUE THREAD

**Issue by happyjin** [gsig/PyVideoResearch#18]
Hi,
Thanks for your awesome project! I have a question about a piece of code: 
`videos = glob.glob('videos/*.mp4')`
This means the ffmpeg command only focus on '.mp4' format video. However, there are also '.mp4' but also '.webm' and '.mkv' which can not be covered by this code. Will it lose videos which have '.mkv' and '.webm' format? Am I right? 

Best,

**Comment by gsig** [comment]
Good catch! In any case, ffmpeg should be able to handle .mkv and .webm as well, so changing the line to `videos = glob.glob('video/*.???')` should do the trick. Let me know if that works, and definitely send a pull request if you find anything that needs improving!

Best,
Gunnar

**Comment by MahdiKalayeh** [comment]
The way that the FOR loop is implemented, ffmpeg should load the entire video in order to clip one snippet. This is extremely inefficient as the same loading process is repeated for roughly (1798-902)/3 times per single video. Were you able to find a more efficient way that also does not sacrifice the frame accuracy?

**Comment by gsig** [comment]
@MahdiKalayeh exactly, I tested other options but wasn't able to get the frame accuracy good enough.
