### ISSUE TITLE
Question about group_size in non_local_block3d.py

### ISSUE THREAD

**Issue by tea1528** [gsig/PyVideoResearch#19]
Hi, I have a question about group_size argument for your non local block.

https://github.com/gsig/PyVideoResearch/blob/46307b1a03ce670696297e2154ddee6f4e6b0b8a/models/layers/nonlocal_block_3d.py#L18

In the original paper and [AlexHe7's repo](https://github.com/AlexHex7/Non-local_pytorch/blob/master/lib/non_local_embedded_gaussian.py), there is no mention of such argument.

Can you explain bit more about its purpose?

Thank you.

**Comment by gsig** [comment]
You can see the implementation of group_size in the original paper's repo (caffe2) https://github.com/facebookresearch/video-nonlocal-net/blob/c253ed5eb004fa2cae0490ed46f5018a3c3b060f/lib/models/nonlocal_helper.py#L153
I just followed this. AlexHe7's repo didn't implement this, but it is mentioned in the original paper, and is crucial for using it for larger feature maps. 

If I remember correctly, it operates similarly to the groups parameter in regular 3d convolutions ( https://pytorch.org/docs/stable/nn.html#convolution-layers ), except this specifies the size instead of the number.

Hope that helps!

**Comment by tea1528** [comment]
Thanks for the clarification!
